# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Child5.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1136, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1141, 861))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_29 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_29.setGeometry(QtCore.QRect(10, 10, 551, 621))
        self.groupBox_29.setObjectName("groupBox_29")
        self.label_4 = QtWidgets.QLabel(self.groupBox_29)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_29)
        self.spinBox.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.spinBox.setObjectName("spinBox")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 60, 91, 31))
        self.lineEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_29)
        self.label_5.setGeometry(QtCore.QRect(290, 30, 91, 20))
        self.label_5.setObjectName("label_5")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_29)
        self.spinBox_2.setGeometry(QtCore.QRect(290, 60, 91, 31))
        self.spinBox_2.setObjectName("spinBox_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit_5.setGeometry(QtCore.QRect(410, 60, 81, 31))
        self.lineEdit_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label = QtWidgets.QLabel(self.groupBox_29)
        self.label.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.label.setObjectName("label")
        self.SelectFileBtn = QtWidgets.QPushButton(self.groupBox_29)
        self.SelectFileBtn.setGeometry(QtCore.QRect(20, 160, 93, 28))
        self.SelectFileBtn.setObjectName("SelectFileBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit.setGeometry(QtCore.QRect(140, 160, 351, 31))
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox_29)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 111, 16))
        self.label_3.setObjectName("label_3")
        self.SaveFileBtn = QtWidgets.QPushButton(self.groupBox_29)
        self.SaveFileBtn.setGeometry(QtCore.QRect(20, 270, 93, 28))
        self.SaveFileBtn.setObjectName("SaveFileBtn")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 270, 351, 31))
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_29)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 111, 16))
        self.label_2.setObjectName("label_2")
        self.SelectSaveAdressBtn = QtWidgets.QPushButton(self.groupBox_29)
        self.SelectSaveAdressBtn.setGeometry(QtCore.QRect(20, 380, 93, 28))
        self.SelectSaveAdressBtn.setObjectName("SelectSaveAdressBtn")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 380, 351, 31))
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_29)
        self.label_8.setGeometry(QtCore.QRect(20, 450, 111, 16))
        self.label_8.setObjectName("label_8")
        self.NameBtn = QtWidgets.QPushButton(self.groupBox_29)
        self.NameBtn.setGeometry(QtCore.QRect(20, 480, 93, 28))
        self.NameBtn.setObjectName("NameBtn")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 480, 351, 31))
        self.lineEdit_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.ConfirmBtn = QtWidgets.QPushButton(self.groupBox_29)
        self.ConfirmBtn.setGeometry(QtCore.QRect(400, 550, 93, 28))
        self.ConfirmBtn.setObjectName("ConfirmBtn")
        self.groupBox_30 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_30.setGeometry(QtCore.QRect(590, 10, 531, 621))
        self.groupBox_30.setObjectName("groupBox_30")
        self.ConfirmBtn_2 = QtWidgets.QPushButton(self.groupBox_30)
        self.ConfirmBtn_2.setGeometry(QtCore.QRect(400, 550, 93, 28))
        self.ConfirmBtn_2.setObjectName("ConfirmBtn_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_30)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_6.setObjectName("label_6")
        self.SelectFileBtn_2 = QtWidgets.QPushButton(self.groupBox_30)
        self.SelectFileBtn_2.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.SelectFileBtn_2.setObjectName("SelectFileBtn_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_30)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 60, 331, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_30)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 72, 15))
        self.label_7.setObjectName("label_7")
        self.SelectTypeBtn = QtWidgets.QPushButton(self.groupBox_30)
        self.SelectTypeBtn.setGeometry(QtCore.QRect(20, 170, 93, 28))
        self.SelectTypeBtn.setObjectName("SelectTypeBtn")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_30)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 170, 131, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(490, 10, 631, 671))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 631, 671))
        self.label_15.setObjectName("label_15")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 451, 161))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.label_16.setObjectName("label_16")
        self.SelectFileBtn_3 = QtWidgets.QPushButton(self.groupBox_8)
        self.SelectFileBtn_3.setGeometry(QtCore.QRect(20, 50, 93, 28))
        self.SelectFileBtn_3.setObjectName("SelectFileBtn_3")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_15.setGeometry(QtCore.QRect(130, 50, 301, 31))
        self.lineEdit_15.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.label_19.setObjectName("label_19")
        self.SelectPhoto = QtWidgets.QPushButton(self.groupBox_8)
        self.SelectPhoto.setGeometry(QtCore.QRect(20, 120, 93, 28))
        self.SelectPhoto.setObjectName("SelectPhoto")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_16.setGeometry(QtCore.QRect(130, 120, 301, 31))
        self.lineEdit_16.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 180, 451, 291))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_38 = QtWidgets.QLabel(self.groupBox_9)
        self.label_38.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.label_38.setObjectName("label_38")
        self.AdjustBtn = QtWidgets.QPushButton(self.groupBox_9)
        self.AdjustBtn.setGeometry(QtCore.QRect(20, 50, 93, 28))
        self.AdjustBtn.setObjectName("AdjustBtn")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_12.setObjectName("label_12")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_3.setGeometry(QtCore.QRect(20, 120, 46, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_11.setGeometry(QtCore.QRect(90, 120, 51, 21))
        self.lineEdit_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setGeometry(QtCore.QRect(220, 90, 72, 15))
        self.label_28.setObjectName("label_28")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_4.setGeometry(QtCore.QRect(220, 120, 46, 22))
        self.spinBox_4.setObjectName("spinBox_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_12.setGeometry(QtCore.QRect(290, 120, 51, 21))
        self.lineEdit_12.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_29 = QtWidgets.QLabel(self.groupBox_9)
        self.label_29.setGeometry(QtCore.QRect(20, 160, 72, 15))
        self.label_29.setObjectName("label_29")
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_7.setGeometry(QtCore.QRect(20, 190, 46, 22))
        self.spinBox_7.setObjectName("spinBox_7")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_23.setGeometry(QtCore.QRect(90, 190, 51, 21))
        self.lineEdit_23.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_11 = QtWidgets.QLabel(self.groupBox_9)
        self.label_11.setGeometry(QtCore.QRect(340, 220, 101, 16))
        self.label_11.setObjectName("label_11")
        self.ConfirmBtn_8 = QtWidgets.QPushButton(self.groupBox_9)
        self.ConfirmBtn_8.setGeometry(QtCore.QRect(340, 250, 93, 28))
        self.ConfirmBtn_8.setObjectName("ConfirmBtn_8")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 480, 451, 241))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_17 = QtWidgets.QLabel(self.groupBox_10)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label_17.setObjectName("label_17")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton.setGeometry(QtCore.QRect(20, 50, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 80, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 110, 72, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 140, 115, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_5.setGeometry(QtCore.QRect(220, 50, 115, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_6.setGeometry(QtCore.QRect(220, 80, 115, 19))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_7.setGeometry(QtCore.QRect(220, 110, 115, 19))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_8.setGeometry(QtCore.QRect(220, 140, 115, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.label_18 = QtWidgets.QLabel(self.groupBox_10)
        self.label_18.setGeometry(QtCore.QRect(340, 170, 141, 16))
        self.label_18.setObjectName("label_18")
        self.ConfirmBtn_4 = QtWidgets.QPushButton(self.groupBox_10)
        self.ConfirmBtn_4.setGeometry(QtCore.QRect(340, 200, 93, 28))
        self.ConfirmBtn_4.setObjectName("ConfirmBtn_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 10, 631, 671))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(0, 0, 631, 671))
        self.label_22.setObjectName("label_22")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 530, 451, 251))
        self.groupBox_4.setObjectName("groupBox_4")
        self.SelectPhoto_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.SelectPhoto_3.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.SelectPhoto_3.setObjectName("SelectPhoto_3")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_17.setGeometry(QtCore.QRect(130, 60, 301, 31))
        self.lineEdit_17.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 72, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_21.setObjectName("label_21")
        self.SelectPhoto_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.SelectPhoto_4.setGeometry(QtCore.QRect(20, 160, 93, 28))
        self.SelectPhoto_4.setObjectName("SelectPhoto_4")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(130, 160, 301, 31))
        self.lineEdit_18.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.ConfirmBtn_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.ConfirmBtn_5.setGeometry(QtCore.QRect(340, 210, 93, 28))
        self.ConfirmBtn_5.setObjectName("ConfirmBtn_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 451, 251))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_30.setObjectName("label_30")
        self.SelectFileBtn_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.SelectFileBtn_5.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.SelectFileBtn_5.setObjectName("SelectFileBtn_5")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_24.setGeometry(QtCore.QRect(130, 60, 301, 31))
        self.lineEdit_24.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(30, 130, 81, 16))
        self.label_31.setObjectName("label_31")
        self.SelectSaveAdressBtn_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.SelectSaveAdressBtn_4.setGeometry(QtCore.QRect(20, 160, 93, 28))
        self.SelectSaveAdressBtn_4.setObjectName("SelectSaveAdressBtn_4")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_25.setGeometry(QtCore.QRect(130, 160, 301, 31))
        self.lineEdit_25.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.ConfirmBtn_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.ConfirmBtn_9.setGeometry(QtCore.QRect(340, 210, 93, 28))
        self.ConfirmBtn_9.setObjectName("ConfirmBtn_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 270, 451, 251))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_32 = QtWidgets.QLabel(self.groupBox_6)
        self.label_32.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_32.setObjectName("label_32")
        self.SelectPhoto_6 = QtWidgets.QPushButton(self.groupBox_6)
        self.SelectPhoto_6.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.SelectPhoto_6.setObjectName("SelectPhoto_6")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_26.setGeometry(QtCore.QRect(130, 60, 301, 31))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        self.label_33.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_33.setObjectName("label_33")
        self.SelectSaveAdressBtn_5 = QtWidgets.QPushButton(self.groupBox_6)
        self.SelectSaveAdressBtn_5.setGeometry(QtCore.QRect(20, 160, 93, 28))
        self.SelectSaveAdressBtn_5.setObjectName("SelectSaveAdressBtn_5")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_27.setGeometry(QtCore.QRect(130, 160, 301, 31))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.ConfirmBtn_10 = QtWidgets.QPushButton(self.groupBox_6)
        self.ConfirmBtn_10.setGeometry(QtCore.QRect(340, 210, 93, 28))
        self.ConfirmBtn_10.setObjectName("ConfirmBtn_10")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(490, 10, 631, 671))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_60 = QtWidgets.QLabel(self.groupBox_7)
        self.label_60.setGeometry(QtCore.QRect(0, 0, 631, 671))
        self.label_60.setObjectName("label_60")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 10, 451, 331))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox_11)
        self.label_9.setGeometry(QtCore.QRect(20, 30, 111, 16))
        self.label_9.setObjectName("label_9")
        self.SelectFileBtn_4 = QtWidgets.QPushButton(self.groupBox_11)
        self.SelectFileBtn_4.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.SelectFileBtn_4.setObjectName("SelectFileBtn_4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_9.setGeometry(QtCore.QRect(130, 60, 301, 31))
        self.lineEdit_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_11)
        self.label_10.setGeometry(QtCore.QRect(30, 120, 72, 15))
        self.label_10.setObjectName("label_10")
        self.NameBtn_2 = QtWidgets.QPushButton(self.groupBox_11)
        self.NameBtn_2.setGeometry(QtCore.QRect(20, 150, 93, 28))
        self.NameBtn_2.setObjectName("NameBtn_2")
        self.label_59 = QtWidgets.QLabel(self.groupBox_11)
        self.label_59.setGeometry(QtCore.QRect(20, 210, 91, 16))
        self.label_59.setObjectName("label_59")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 150, 301, 31))
        self.lineEdit_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.SelectSaveAdressBtn_3 = QtWidgets.QPushButton(self.groupBox_11)
        self.SelectSaveAdressBtn_3.setGeometry(QtCore.QRect(20, 240, 93, 28))
        self.SelectSaveAdressBtn_3.setObjectName("SelectSaveAdressBtn_3")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_45.setGeometry(QtCore.QRect(130, 240, 301, 31))
        self.lineEdit_45.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_45.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 350, 451, 261))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_12)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.label_13.setObjectName("label_13")
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_12)
        self.spinBox_5.setGeometry(QtCore.QRect(20, 80, 91, 31))
        self.spinBox_5.setObjectName("spinBox_5")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 80, 71, 31))
        self.lineEdit_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_12)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.label_14.setObjectName("label_14")
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_12)
        self.spinBox_6.setGeometry(QtCore.QRect(20, 170, 91, 31))
        self.spinBox_6.setObjectName("spinBox_6")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_14.setGeometry(QtCore.QRect(140, 170, 71, 31))
        self.lineEdit_14.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.ConfirmBtn_7 = QtWidgets.QPushButton(self.groupBox_12)
        self.ConfirmBtn_7.setGeometry(QtCore.QRect(320, 220, 93, 28))
        self.ConfirmBtn_7.setObjectName("ConfirmBtn_7")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 10, 631, 671))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 631, 671))
        self.label_27.setObjectName("label_27")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 10, 451, 261))
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_26 = QtWidgets.QLabel(self.groupBox_13)
        self.label_26.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_26.setObjectName("label_26")
        self.SelectVideo = QtWidgets.QPushButton(self.groupBox_13)
        self.SelectVideo.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.SelectVideo.setObjectName("SelectVideo")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_22.setGeometry(QtCore.QRect(130, 60, 301, 31))
        self.lineEdit_22.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_25 = QtWidgets.QLabel(self.groupBox_13)
        self.label_25.setGeometry(QtCore.QRect(20, 130, 101, 16))
        self.label_25.setObjectName("label_25")
        self.SelectVideo_2 = QtWidgets.QPushButton(self.groupBox_13)
        self.SelectVideo_2.setGeometry(QtCore.QRect(20, 160, 93, 28))
        self.SelectVideo_2.setObjectName("SelectVideo_2")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_21.setGeometry(QtCore.QRect(130, 160, 301, 31))
        self.lineEdit_21.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.CombineBtn = QtWidgets.QPushButton(self.groupBox_13)
        self.CombineBtn.setGeometry(QtCore.QRect(340, 220, 93, 28))
        self.CombineBtn.setObjectName("CombineBtn")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 290, 451, 271))
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_23 = QtWidgets.QLabel(self.groupBox_14)
        self.label_23.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label_23.setObjectName("label_23")
        self.SelectPhoto_5 = QtWidgets.QPushButton(self.groupBox_14)
        self.SelectPhoto_5.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.SelectPhoto_5.setObjectName("SelectPhoto_5")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_19.setGeometry(QtCore.QRect(130, 60, 301, 31))
        self.lineEdit_19.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_24 = QtWidgets.QLabel(self.groupBox_14)
        self.label_24.setGeometry(QtCore.QRect(20, 130, 72, 20))
        self.label_24.setObjectName("label_24")
        self.SelectLogo = QtWidgets.QPushButton(self.groupBox_14)
        self.SelectLogo.setGeometry(QtCore.QRect(20, 160, 93, 28))
        self.SelectLogo.setObjectName("SelectLogo")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_20.setGeometry(QtCore.QRect(130, 160, 301, 31))
        self.lineEdit_20.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.ConfirmBtn_6 = QtWidgets.QPushButton(self.groupBox_14)
        self.ConfirmBtn_6.setGeometry(QtCore.QRect(340, 220, 93, 28))
        self.ConfirmBtn_6.setObjectName("ConfirmBtn_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spinBox, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.spinBox_2)
        MainWindow.setTabOrder(self.spinBox_2, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.SelectFileBtn)
        MainWindow.setTabOrder(self.SelectFileBtn, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.SaveFileBtn)
        MainWindow.setTabOrder(self.SaveFileBtn, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.SelectSaveAdressBtn)
        MainWindow.setTabOrder(self.SelectSaveAdressBtn, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.ConfirmBtn)
        MainWindow.setTabOrder(self.ConfirmBtn, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Step1"))
        self.label_4.setText(_translate("MainWindow", "选择阈值"))
        self.label_5.setText(_translate("MainWindow", "选择刷新时间"))
        self.label.setText(_translate("MainWindow", "选择文件夹"))
        self.SelectFileBtn.setText(_translate("MainWindow", "浏览"))
        self.label_3.setText(_translate("MainWindow", "选择保存的文件"))
        self.SaveFileBtn.setText(_translate("MainWindow", "浏览"))
        self.label_2.setText(_translate("MainWindow", "保存的地址"))
        self.SelectSaveAdressBtn.setText(_translate("MainWindow", "浏览"))
        self.label_8.setText(_translate("MainWindow", "保存的文件夹名"))
        self.NameBtn.setText(_translate("MainWindow", "点击命名"))
        self.ConfirmBtn.setText(_translate("MainWindow", "确认"))
        self.groupBox_30.setTitle(_translate("MainWindow", "Step2"))
        self.ConfirmBtn_2.setText(_translate("MainWindow", "确认"))
        self.label_6.setText(_translate("MainWindow", "选择文件夹"))
        self.SelectFileBtn_2.setText(_translate("MainWindow", "浏览"))
        self.label_7.setText(_translate("MainWindow", "排序方式"))
        self.SelectTypeBtn.setText(_translate("MainWindow", "选择"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "初步处理"))
        self.label_15.setText(_translate("MainWindow", "                                  图片预览区"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Step1"))
        self.label_16.setText(_translate("MainWindow", "选择图片文件夹"))
        self.SelectFileBtn_3.setText(_translate("MainWindow", "浏览"))
        self.label_19.setText(_translate("MainWindow", "选择图片"))
        self.SelectPhoto.setText(_translate("MainWindow", "浏览"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Step2"))
        self.label_38.setText(_translate("MainWindow", "锐度、饱和度调整"))
        self.AdjustBtn.setText(_translate("MainWindow", "开始调试"))
        self.label_12.setText(_translate("MainWindow", "输入对比度"))
        self.label_28.setText(_translate("MainWindow", "输入亮度"))
        self.label_29.setText(_translate("MainWindow", "输入锐度"))
        self.label_11.setText(_translate("MainWindow", "是否全部应用"))
        self.ConfirmBtn_8.setText(_translate("MainWindow", "确定"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Step3"))
        self.label_17.setText(_translate("MainWindow", "选择滤镜"))
        self.radioButton.setText(_translate("MainWindow", "滤镜一"))
        self.radioButton_2.setText(_translate("MainWindow", "滤镜二"))
        self.radioButton_3.setText(_translate("MainWindow", "滤镜三"))
        self.radioButton_4.setText(_translate("MainWindow", "滤镜四"))
        self.radioButton_5.setText(_translate("MainWindow", "滤镜五"))
        self.radioButton_6.setText(_translate("MainWindow", "滤镜六"))
        self.radioButton_7.setText(_translate("MainWindow", "滤镜七"))
        self.radioButton_8.setText(_translate("MainWindow", "滤镜八"))
        self.label_18.setText(_translate("MainWindow", "是否全部应用"))
        self.ConfirmBtn_4.setText(_translate("MainWindow", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "图像处理①"))
        self.label_22.setText(_translate("MainWindow", "                                  图片预览区"))
        self.groupBox_4.setTitle(_translate("MainWindow", "图片扣绿"))
        self.SelectPhoto_3.setText(_translate("MainWindow", "选择"))
        self.label_20.setText(_translate("MainWindow", "选择图片"))
        self.label_21.setText(_translate("MainWindow", "选择背景"))
        self.SelectPhoto_4.setText(_translate("MainWindow", "选择"))
        self.ConfirmBtn_5.setText(_translate("MainWindow", "确定"))
        self.groupBox_5.setTitle(_translate("MainWindow", "防抖处理"))
        self.label_30.setText(_translate("MainWindow", "选择图片所在文件夹"))
        self.SelectFileBtn_5.setText(_translate("MainWindow", "浏览"))
        self.label_31.setText(_translate("MainWindow", "保存的位置"))
        self.SelectSaveAdressBtn_4.setText(_translate("MainWindow", "浏览"))
        self.ConfirmBtn_9.setText(_translate("MainWindow", "开始处理"))
        self.groupBox_6.setTitle(_translate("MainWindow", "图片剪裁"))
        self.label_32.setText(_translate("MainWindow", "选择图片"))
        self.SelectPhoto_6.setText(_translate("MainWindow", "选择"))
        self.label_33.setText(_translate("MainWindow", "保存的位置"))
        self.SelectSaveAdressBtn_5.setText(_translate("MainWindow", "浏览"))
        self.ConfirmBtn_10.setText(_translate("MainWindow", "开始处理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "图像处理②"))
        self.label_60.setText(_translate("MainWindow", "                                  视频预览区"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Step1"))
        self.label_9.setText(_translate("MainWindow", "选择图片文件夹"))
        self.SelectFileBtn_4.setText(_translate("MainWindow", "浏览"))
        self.label_10.setText(_translate("MainWindow", "命名视频"))
        self.NameBtn_2.setText(_translate("MainWindow", "点击命名"))
        self.label_59.setText(_translate("MainWindow", "选择保存位置"))
        self.SelectSaveAdressBtn_3.setText(_translate("MainWindow", "浏览"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Step2"))
        self.label_13.setText(_translate("MainWindow", "设定帧数"))
        self.label_14.setText(_translate("MainWindow", "重复次数"))
        self.ConfirmBtn_7.setText(_translate("MainWindow", "确认"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "视频合成"))
        self.label_27.setText(_translate("MainWindow", "                                  视频展示区"))
        self.groupBox_13.setTitle(_translate("MainWindow", "视频拼接"))
        self.label_26.setText(_translate("MainWindow", "选择合成后的视频"))
        self.SelectVideo.setText(_translate("MainWindow", "选择"))
        self.label_25.setText(_translate("MainWindow", "选择一段视频"))
        self.SelectVideo_2.setText(_translate("MainWindow", "选择"))
        self.CombineBtn.setText(_translate("MainWindow", "拼接"))
        self.groupBox_14.setTitle(_translate("MainWindow", "添加水印"))
        self.label_23.setText(_translate("MainWindow", "选择图片"))
        self.SelectPhoto_5.setText(_translate("MainWindow", "浏览"))
        self.label_24.setText(_translate("MainWindow", "选择水印"))
        self.SelectLogo.setText(_translate("MainWindow", "浏览"))
        self.ConfirmBtn_6.setText(_translate("MainWindow", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "后期处理"))

